### ISSUE TITLE
Simplify "install package into Blender" instructions

### ISSUE THREAD

**Issue by zooba** [Azure/azure-batch-apps-blender#1]
The instructions in the readme file (shown on the front page) suggest installing the Python package and then copying into Blender's folder, or extracting the package into the location. ([Example](https://pytools.codeplex.com/discussions/579708) of someone needing more help with the instructions.)

These could be simplified to a single command line with `pip install --root <path>`. I don't have it all set up, so I can't test it to figure out exactly what `<path>` should be, but that should be able to install directly into the required location.

**Comment by davefellows** [comment]
Thanks Steve, good suggestion! Will ask Anna to look at this when she gets back from vacation next week.

**Comment by annatisch** [comment]
Thanks Steve - I'll update this today :)
Should this be --target instead of --root? Using root seems to append the python installation prefix onto my chosen directory... does this behave differently depending on OS?

**Comment by zooba** [comment]
Possibly it should be `--target` - as I said, I didn't test it. Go ahead and do whatever works :)

**Comment by annatisch** [comment]
Sweet - pushed this cleanup public now.
Thank you! :)
