### ISSUE TITLE
Having problems making it run

### ISSUE THREAD

**Issue by matvelloso** [Azure/azure-batch-apps-blender#2]
Followed all steps bit it's not working. Two issues:

1-When uploading blender.zip to the portal the upload goes all the way to the end and then tells me there was an error uploading the file. It won't tell me what error or give me any details. But if I refresh the page the file is there. Did it upload or not?

2-Installed the addon but it keeps showing "addon failed to load correctly". I reviewed all configurations, everything looks fine but it keeps showing me that error. The console won't show anything in addition. How do I find out the reason for the failure?

Thanks

**Comment by matvelloso** [comment]
Also: 
3-The link https://github.com/Azure/azure-batch-apps-blender/blob/master/pypi.python.org in readme doesn't seem to exist.

**Comment by annatisch** [comment]
Hi Mat,

Thanks for your message.
I have a few questions, which will hopefully help us get this sorted out for you ASAP.

For the first issue - I'll notify those who developed the portal, so will hopefully get a response soon.
A few questions:
Is the Blender.zip you're uploading the application image (e.g. containing blender.exe etc), or the assemblies (containing Blender.Cloud.dll etc)?
Did you build the assemblies in Blender.zip locally, or are they the compiled ones downloaded from the release?

For the second - Which OS are you running the addon with? The "failed to load" message occurs when an error occurs during initialization.
This may happen if Blender doesn't have permission to write to the directory where it creates a log file. You could try running Blender as an administrator.

In the console, you should see printed:
BatchApps Addon failed to load.
Error: (error details here)

Are there no further details printed on the second line?
Alternatively, the log file should be stored in the same directory as the configuration file (assuming that it was not on creating the log that the error occurred), which by default will be $HOME/BatchAppsData/batch_apps.log.
There may be additional information in this file that will help us ascertain the cause.

Issue 3: You're quite right, that URL seems to be pretty bungled, I'll get that fixed up :)

Regards,
Anna

**Comment by matvelloso** [comment]
Hello,

The Blender.zip is the one with blender.exe. I've learned I can upload it with Chrome, but not with IE on Windows 10 Preview. It always fails at the end.

The failed to load was due to the missing BatchAppsData folder that needs to be created according to the setting (posted as another issue).

Thanks!

**Comment by annatisch** [comment]
Hello,

Thanks - I will send this feedback re failed uploads to the portal team.
As per the BatchAppsData folder issue post - I will continue you investigate this further, and update you as soon as I have more info, and hopefully a fix in place for this one :)

Thanks for all your feedback!
Regards,
Anna
