### ISSUE TITLE
Plugin won't launch unless BatchAppsData folder is manually created

### ISSUE THREAD

**Issue by matvelloso** [Azure/azure-batch-apps-blender#3]
The instructions should point that out. Took me a while to figure that was the problem.

**Comment by annatisch** [comment]
Thanks Mat,

This shouldn't be necessary, and one of my colleagues encountered similar behavior. I will investigate this further and amend the instructions and the code as necessary.

**Comment by annatisch** [comment]
I've located this bug and committed a fix: 390bef7f2f8c2e8a217ee4c4f265f841b4335091
In the case that the user genuinely does not have permission to create the data directory, I have also slightly improved the error message to at least specify where it attempted to create the directory.

Thanks!
