### ISSUE TITLE
The service is rendering all frames blank

### ISSUE THREAD

**Issue by matvelloso** [Azure/azure-batch-apps-blender#5]
After configuring everything, uploading all my assets and setting the service to render I realize now that all frames are being rendered blank. Same project renders fine on my machine. Is there any additional setting I need to do?

**Comment by annatisch** [comment]
Hi Mat,

There a several potential reasons - it could be an issue in the data supplied by the client, or it could be an issue  Blender on the cloud.

I would recommend starting by putting the addon in debug mode.
This is a setting found under the addon entry in User Preferences. By default it's set to 'Warning', but you can set to 'Debug', save settings then restart Blender.
This will ensure all the steps in submitting a job a printed to the console, and also saved to the log file.

In particular I would check through this to ensure all the files in your scene are being detected and uploaded correctly.

Another debugging tool you have is the ability to download the processor log (i.e. the Blender stdout) through the Batch Apps portal. This will let you know if Blender encountered any problems in rendering the file.

Let me know if you have further questions :)

Cheers,
Anna

**Comment by matvelloso** [comment]
I'll take a look at those. Thanks

**Comment by matvelloso** [comment]
Follow up: It sounds like what I missed here was to going to assets in the plugin's menu and re-uploading the blender project with the remaining assets. Thanks
