### ISSUE TITLE
Azure new portal, miss match client ID

### ISSUE THREAD

**Issue by icdsarch** [Azure/azure-batch-apps-blender#6]
`2016-06-15 13:14:37,965 [ERROR] exceptions: InvalidConfigException: Unattended Account must be in the format 'ClientID=abc;TenantID=xyz'` 

I am seeing a problem with the new portal, as some of the features are not matching configurations with blender.

Can you let me know, how do I get the Unattended Account and account ID?? in the NEW azure portal???

**Comment by itowlson** [comment]
The Batch Apps portal is not incorporated into the portal.azure.com portal; you'll need to access it separately.  To do this, visit https://manage.batchapps.windows.net/Services.  You can then select your Batch Apps account and click View Details > Unattended Account.

**Comment by icdsarch** [comment]
Well, the list is empty, for some reason wouldn't let me register a new app in the old portal, while in the new portal I have the app listed. I think azure is miss configured. 

> Account creation not supported at this time
> The Azure Batch Apps preview is closed for new accounts. Please use the released Azure Batch service API. It will be updated regularly with new capabilities including features that were in the Batch Apps preview.
