### ISSUE TITLE
batched blender - dll load failed

### ISSUE THREAD

**Issue by a1rohner** [Azure/azure-batch-apps-blender#9]
Dear Annatisch,

I'm trying to install Batched Blender 0.2.0 for colleague who's doing eLearning videos with blender. The situation is that i installed it on my computer without any issues but trying to install it on his laptop, which is an office note book, hence same windows version and I got an Error similar to the one, which has been already discussed here for Azure-Batch-Apps-Blender.

Do you have an idea how to fix this?

![blenderbatcherror](https://cloud.githubusercontent.com/assets/23740621/20626764/0d65ac88-b31c-11e6-942c-f206e927d0fc.png)

**Comment by annatisch** [comment]
Hi @a1rohner - thanks!
I looks like some trouble running the Cryptography lib - this is a dependency of Azure Storage 0.33+.
I would recommend trying to run with Azure Storage 0.32.0 for the time being.

I have pushed some changes into my dev branch recently that should handle dependency installation for you (provided Blender is run with administrator privileges).

Let me know how that goes and if you still run into installation difficulties!

**Comment by a1rohner** [comment]
Hi annatisch,

Thanks a lot for your support. I saw that the installed version of azure storage is 0.33.0. How can I change the version of this storage? And maybe would be a good approach to understand the issue better, where can I check the version of this storage running on my machine, where blender batch works?

I tried to install blender with the newest updated version of your code. I still ran into the same problems but as mentioned with storage version 0.33.0.

Thanks for your support and time.
best wishes
Adrian

**Comment by annatisch** [comment]
Hi @a1rohner,

To be honest the easiest way to change it is simply to go into Blender/2.78/python/lib/site-package/azure and delete the storage directory (or delete the whole azure directory and reinstall Batch as well).
Then reinstall using "pip install azure-storage==0.32.0".
My updated code should install dependencies.... but I haven't tested it for rolling back dependency versions.... 

Let me know if this gets everything working :)
Cheers,
Anna

**Comment by a1rohner** [comment]
Hi annatisch,

Yeaaaaaaaaaaaah. It worked. Thanks a lot for your support. We will now test it with some use cases, but as I guess it will be a much more comfortable solution then using two, three single vm's at the same time, as we managed it until now.

best wishes
Adrian

**Comment by annatisch** [comment]
@a1rohner,

Awesome! Good to hear :)
We really appreciate any feedback and bug reports you have on the plugin - I've been adding a few features recently and am nearly happy to push my branch back to master.
